cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/tsesterh/Dokumente/ns-3-gsoc/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/home/tsesterh/Dokumente/ns-3-gsoc/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139632461888208: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'_Wall\', \'-fwrapv\', \'-fwrapv\', \'-fstack-protector-strong\', \'-fwrapv\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python3/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python3/dist-packages"\', \'-DNDEBUG\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
