cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/tsesterh/Dokumente/ns-3-gsoc/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/home/tsesterh/Dokumente/ns-3-gsoc/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140536109949840: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-Bsymbolic-functions\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/tsesterh/Dokumente/ns-3-gsoc/build/.conf_check_47edc30cf74b5b20788533ecb328dd94/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib/python2.7/config-x86_64-linux-gnu\', \'-lpython2.7m\']\n'
